In [14]:
#Dataset shows different Countries with their Various Flags
#Dataset contains 10 Attribute

#My model is to predict The religion of Each country by 
#the Size and color of Flag

In [1]:
import pandas as pd
import numpy as np

#Use pandas to open the dataset

df = pd.read_csv('flag.data')
print(df)

        Afghanistan  5  1   648  16  10  2  0  3  5.1  ...  0.5  0.6  1.6  \
0           Albania  3  1    29   3   6  6  0  0    3  ...    0    0    1   
1           Algeria  4  1  2388  20   8  2  2  0    3  ...    0    0    1   
2    American-Samoa  6  3     0   0   1  1  0  0    5  ...    0    0    0   
3           Andorra  3  1     0   0   6  0  3  0    3  ...    0    0    0   
4            Angola  4  2  1247   7  10  5  0  2    3  ...    0    0    1   
..              ... .. ..   ...  ..  .. .. .. ..  ...  ...  ...  ...  ...   
188   Western-Samoa  6  3     3   0   1  1  0  0    3  ...    0    1    5   
189      Yugoslavia  3  1   256  22   6  6  0  3    4  ...    0    0    1   
190           Zaire  4  2   905  28  10  5  0  0    4  ...    0    0    0   
191          Zambia  4  2   753   6  10  5  3  0    4  ...    0    0    0   
192        Zimbabwe  4  2   391   8  10  5  0  7    5  ...    0    0    1   

     0.7  0.8  1.7  0.9 0.10  black  green.1  
0      0    0    0    1    0

In [2]:
df

Afghanistan  5  1   648  16  10  2  0  3  5.1  ...  0.5  0.6  1.6  \
0           Albania  3  1    29   3   6  6  0  0    3  ...    0    0    1   
1           Algeria  4  1  2388  20   8  2  2  0    3  ...    0    0    1   
2    American-Samoa  6  3     0   0   1  1  0  0    5  ...    0    0    0   
3           Andorra  3  1     0   0   6  0  3  0    3  ...    0    0    0   
4            Angola  4  2  1247   7  10  5  0  2    3  ...    0    0    1   
..              ... .. ..   ...  ..  .. .. .. ..  ...  ...  ...  ...  ...   
188   Western-Samoa  6  3     3   0   1  1  0  0    3  ...    0    1    5   
189      Yugoslavia  3  1   256  22   6  6  0  3    4  ...    0    0    1   
190           Zaire  4  2   905  28  10  5  0  0    4  ...    0    0    0   
191          Zambia  4  2   753   6  10  5  3  0    4  ...    0    0    0   
192        Zimbabwe  4  2   391   8  10  5  0  7    5  ...    0    0    1   

     0.7  0.8  1.7  0.9 0.10  black  green.1  
0      0    0    0    1    0    red      red  
1      1    0    0    0    0  green    white  
2      0    1    1    1    0   blue      red  
3      0    0    0    0    0   blue      red  
4      0    0    1    0    0    red    black  
..   ...  ...  ...  ...  ...    ...      ...  
188    0    0    0    0    0   blue      red  
189    0    0    0    0    0   blue      red  
190    0    0    1    1    0  green    green  
191    0    0    0    1    0  green    brown  
192    0    1    1    1    0  green    green  

[193 rows x 30 columns]

In [3]:
#Label Encoder to convert values

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
column_names =df.columns.values
for i in range (len(column_names)):
    if df.dtypes[i] == 'object':
        df[column_names[i]] = encoder.fit_transform(df[column_names[i]])
df.head(5)

Afghanistan  5  1   648  16  10  2  0  3  5.1  ...  0.5  0.6  1.6  0.7  \
0            0  3  1    29   3   6  6  0  0    3  ...    0    0    1    0   
1            1  4  1  2388  20   8  2  2  0    3  ...    0    0    1    1   
2            2  6  3     0   0   1  1  0  0    5  ...    0    0    0    0   
3            3  3  1     0   0   6  0  3  0    3  ...    0    0    0    0   
4            4  4  2  1247   7  10  5  0  2    3  ...    0    0    1    0   

   0.8  1.7  0.9  0.10  black  green.1  
0    0    0    1     0      5        6  
1    0    0    0     0      3        7  
2    1    1    1     0      1        6  
3    0    0    0     0      1        6  
4    0    1    0     0      5        0  

[5 rows x 30 columns]

In [4]:
data = df.values

In [5]:
y = df.values[:,6]
y.shape
y

array([6, 2, 1, 0, 5, 1, 1, 0, 0, 1, 0, 1, 2, 2, 1, 0, 1, 5, 1, 3, 0, 5,
       0, 1, 2, 6, 5, 3, 5, 1, 1, 0, 1, 5, 5, 0, 6, 0, 2, 5, 1, 0, 6, 1,
       6, 1, 2, 1, 0, 0, 2, 0, 5, 1, 1, 1, 1, 1, 0, 0, 0, 5, 5, 6, 1, 5,
       1, 1, 1, 1, 1, 0, 2, 5, 4, 0, 0, 3, 6, 1, 4, 2, 2, 2, 0, 7, 0, 5,
       1, 7, 2, 3, 5, 1, 2, 6, 2, 5, 5, 2, 0, 0, 1, 5, 2, 2, 2, 0, 1, 2,
       4, 0, 1, 0, 6, 1, 2, 5, 1, 4, 1, 1, 1, 0, 2, 2, 1, 6, 2, 1, 2, 2,
       0, 5, 0, 0, 0, 6, 0, 0, 2, 6, 5, 0, 0, 2, 2, 1, 5, 3, 1, 2, 1, 7,
       2, 0, 3, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 3, 5, 3, 7, 1, 1, 2, 2, 1,
       1, 2, 5, 1, 0, 1, 1, 6, 1, 0, 0, 6, 1, 6, 5, 5, 5])

In [6]:
X = df.values[:,0:5]
X.shape
X[:10]

array([[   0,    3,    1,   29,    3],
       [   1,    4,    1, 2388,   20],
       [   2,    6,    3,    0,    0],
       [   3,    3,    1,    0,    0],
       [   4,    4,    2, 1247,    7],
       [   5,    1,    4,    0,    0],
       [   6,    1,    4,    0,    0],
       [   7,    2,    3, 2777,   28],
       [   8,    2,    3, 2777,   28],
       [   9,    6,    2, 7690,   15]])

In [7]:
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()

X = minmax.fit_transform(X)
X[:10]

array([[0.        , 0.4       , 0.        , 0.00129453, 0.00297619],
       [0.00520833, 0.6       , 0.        , 0.10659763, 0.01984127],
       [0.01041667, 1.        , 0.66666667, 0.        , 0.        ],
       [0.015625  , 0.4       , 0.        , 0.        , 0.        ],
       [0.02083333, 0.6       , 0.33333333, 0.05566467, 0.00694444],
       [0.02604167, 0.        , 1.        , 0.        , 0.        ],
       [0.03125   , 0.        , 1.        , 0.        , 0.        ],
       [0.03645833, 0.2       , 0.66666667, 0.12396215, 0.02777778],
       [0.04166667, 0.2       , 0.66666667, 0.12396215, 0.02777778],
       [0.046875  , 1.        , 0.33333333, 0.34327292, 0.01488095]])

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 42)

print(X_train.shape)
print(y_train.shape)

(154, 5)
(154,)


In [9]:
print(X_test.shape)
print(y_test.shape)

(39, 5)
(39,)


In [10]:
#K Nearest Neighbors

In [11]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=3)
# training process
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [12]:
y_pred = model.predict(X_test)
from sklearn import metrics 
acc = metrics.accuracy_score(y_pred,y_test) 
print('accuracy:\n',acc * 100) 

accuracy:
 56.41025641025641


In [13]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) 

In [14]:
#Naive Bayes

In [15]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [16]:
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [18]:
y_pred = model.predict(X_test)
acc = metrics.accuracy_score(y_pred,y_test) 
print('accuracy:\n',acc * 100) 

accuracy:
 28.205128205128204
